server {
    listen 80;
    listen [::]:80;
    server_name ethii.net www.ethii.net _;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /rpc {
        proxy_pass http://91.99.231.217:8545;
    }

    location /api/stats {
        proxy_pass http://127.0.0.1:8082/api/stats;
    }
}
